Lovely-Development-Team/MottoBotto

botto/run_botto.py

This is what happens when you print things for debugging!

Don't log Discord token

---

botto/MottoBotto.py

Added a check to make sure the user suggesting the motto is not the same as the user who posted the motto

Added self-suggestion detection

---

botto/MottoBotto.py

Updating Airtable display name when detecting a change

Added display name updating

---

botto/MottoBotto.py
botto/config.py
botto/run_botto.py

Fix #43 and format with black

---

botto/MottoBotto.py
botto/config.py
botto/run_botto.py

Don't allow numeric only mottos

---

botto/MottoBotto.py
botto/message_checks.py

Make Botto recognise and ignore (for now) direct messages.
Fixes #47

Recognise direct messages

---

.gitignore
botto/run_botto.py
log.conf
logs/.keep

Adds timestamps to logging output, and generates log files.  Closes #83

Logging config

---

botto/MottoBotto.py

Separate method for each update, fixes name updates from DMs where server specific nicknames aren't available

Refactored updating emoji and names

---

botto/MottoBotto.py
botto/config.py
config.json.example
log.conf

Add deleting after hours

---

botto/MottoBotto.py

Fixed disappearing names when nickname is not set

---

botto/MottoBotto.py

Check if `nick` is available before accessing it

---

botto/MottoBotto.py

Optional nickname storage, username updating

---

botto/MottoBotto.py

Fixed mobile mentions bug

---

README.md

Fixed some typos and updated link to use `https://mottobotto.com/`

---

botto/MottoBotto.py
botto/config.py

Fix server specific emoji #173

---

botto/motto_storage.py
botto/run_botto.py

We should really be storing the session, as it contains a connection pool, but I haven't thought of a neat way to do that yet in this context.

Fetch Mottos asynchronously

---

botto/MottoBotto.py
botto/config.py
botto/reactions.py

Added special reactions and baby feature flag

---

botto/MottoBotto.py
botto/motto_storage.py
botto/reactions.py

* Makes the rest of the member fetching concurrent
* Runs nominator/nominee fetching/updating concurrently
* Adds the "party" reactions concurrently

Make more fetching async + some concurrency

---

botto/MottoBotto.py

Added help message for motto excerpts.

---

botto/motto_storage.py

Change default sort order for `_iterate` to desc.
Fixes #230

Fix leaderboard ordering

---

botto/MottoBotto.py

Easter eggs and random removal

---

botto/motto_storage.py

Gives people points for nominating and matches the website

Sort leaderboard by "Total Points" rather than "Motto Count"

---

README.md
botto/MottoBotto.py

Updated the docs and the `!help` message.

Update help message

---

botto/MottoBotto.py

fixes not reacting to non-reply messages issue

removed checking for tags
